name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Création du settings.xml pour Maven
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
              <server>
                <id>github-le-prof-de-raizo</id>
                <username>le-prof-de-raizo</username>
                <password>${{secrets.PROF_TOKEN}}</password> 
              </server>
            </servers>
          </settings>
          EOF

      - name: Compilation et publication (Deploy)
        run: mvn clean deploy -DskipTests